#!/bin/bash



function max2 {
   while [ `jobs | wc -l` -ge 80 ]
   do
      sleep 1
   done
}


set -e 


sbox=4
nr=3
mkdir -p ./iterative_calls_${nr}nr_${sbox}sbox
mkdir -p ./iterative_calls_${nr}nr_${sbox}sbox/results

num=0
take=0
while read p; do
	if [[ "$p" == *-* ]]; then 
		continue
	fi
	if [[ "$p" == *"["* ]]; then 
		echo ${p}
		echo $num
		cp ASCON_v5_Sbox_${nr}rd.mzn ./iterative_calls_${nr}nr_${sbox}sbox/ASCON_v5_Sbox_${num}.mzn
		read sbox1 sbox2 <<< ${p//[^0-9]/ }
		echo "constraint sum(j in 0..63)(bool2int(checkActive([statestart[1,i,j] | i in 0..4]))) = ${sbox1};" >> ./iterative_calls_${nr}nr_${sbox}sbox/ASCON_v5_Sbox_${num}.mzn
		echo "constraint sum(j in 0..63)(bool2int(checkActive([statestart[2,i,j] | i in 0..4]))) = ${sbox2};" >> ./iterative_calls_${nr}nr_${sbox}sbox/ASCON_v5_Sbox_${num}.mzn
		take=1
		continue
	fi
	if [[ ${take} -eq 1 ]]; then # this is the first line
		for ((i=0;i<=${#p};i++)); do
			if [[ ${p:$i:1} == 1 ]]; then
				echo "constraint checkActive([statestart[1,i,${i}] | i in 0..4]) = 1;" >> ./iterative_calls_${nr}nr_${sbox}sbox/ASCON_v5_Sbox_${num}.mzn
			fi
		done
		take=2
		continue
	fi
	if [[ ${take} -eq 2 ]]; then # this is the second line
		for ((i=0;i<=${#p};i++)); do
			if [[ ${p:$i:1} == 1 ]]; then
				echo "constraint checkActive([statestart[2,i,${i}] | i in 0..4]) = 1;" >> ./iterative_calls_${nr}nr_${sbox}sbox/ASCON_v5_Sbox_${num}.mzn
			fi
		done
		take=0
		max2; minizinc --solver "chuffed" -a -D "nr = ${nr};" --time-limit 5400000 --output-time --statistics ./iterative_calls_${nr}nr_${sbox}sbox/ASCON_v5_Sbox_${num}.mzn > ./iterative_calls_${nr}nr_${sbox}sbox/results/ASCON_results_${num}.txt &
		num=$((num + 1))
		echo num $num
	fi
done < ASCON_P_${sbox}.txt


nr=4
mkdir -p ./iterative_calls_${nr}nr_${sbox}sbox
mkdir -p ./iterative_calls_${nr}nr_${sbox}sbox/results

num=0
take=0
while read p; do
	if [[ "$p" == *-* ]]; then 
		continue
	fi
	if [[ "$p" == *"["* ]]; then 
		echo ${p}
		echo $num
		cp ASCON_v5_Sbox_${nr}rd.mzn ./iterative_calls_${nr}nr_${sbox}sbox/ASCON_v5_Sbox_${num}.mzn
		read sbox1 sbox2 <<< ${p//[^0-9]/ }
		echo "constraint sum(j in 0..63)(bool2int(checkActive([statestart[1,i,j] | i in 0..4]))) = ${sbox1};" >> ./iterative_calls_${nr}nr_${sbox}sbox/ASCON_v5_Sbox_${num}.mzn
		echo "constraint sum(j in 0..63)(bool2int(checkActive([statestart[2,i,j] | i in 0..4]))) = ${sbox2};" >> ./iterative_calls_${nr}nr_${sbox}sbox/ASCON_v5_Sbox_${num}.mzn
		take=1
		continue
	fi
	if [[ ${take} -eq 1 ]]; then # this is the first line
		for ((i=0;i<=${#p};i++)); do
			if [[ ${p:$i:1} == 1 ]]; then
				echo "constraint checkActive([statestart[1,i,${i}] | i in 0..4]) = 1;" >> ./iterative_calls_${nr}nr_${sbox}sbox/ASCON_v5_Sbox_${num}.mzn
			fi
		done
		take=2
		continue
	fi
	if [[ ${take} -eq 2 ]]; then # this is the second line
		for ((i=0;i<=${#p};i++)); do
			if [[ ${p:$i:1} == 1 ]]; then
				echo "constraint checkActive([statestart[2,i,${i}] | i in 0..4]) = 1;" >> ./iterative_calls_${nr}nr_${sbox}sbox/ASCON_v5_Sbox_${num}.mzn
			fi
		done
		take=0
		max2; minizinc --solver "chuffed" -a -D "nr = ${nr};" --time-limit 5400000 --output-time --statistics ./iterative_calls_${nr}nr_${sbox}sbox/ASCON_v5_Sbox_${num}.mzn > ./iterative_calls_${nr}nr_${sbox}sbox/results/ASCON_results_${num}.txt &
		num=$((num + 1))
		echo num $num
	fi
done < ASCON_P_${sbox}.txt




nr=5
mkdir -p ./iterative_calls_${nr}nr_${sbox}sbox
mkdir -p ./iterative_calls_${nr}nr_${sbox}sbox/results

num=0
take=0
while read p; do
	if [[ "$p" == *-* ]]; then 
		continue
	fi
	if [[ "$p" == *"["* ]]; then 
		echo ${p}
		echo $num
		cp ASCON_v5_Sbox_${nr}rd.mzn ./iterative_calls_${nr}nr_${sbox}sbox/ASCON_v5_Sbox_${num}.mzn
		read sbox1 sbox2 <<< ${p//[^0-9]/ }
		echo "constraint sum(j in 0..63)(bool2int(checkActive([statestart[1,i,j] | i in 0..4]))) = ${sbox1};" >> ./iterative_calls_${nr}nr_${sbox}sbox/ASCON_v5_Sbox_${num}.mzn
		echo "constraint sum(j in 0..63)(bool2int(checkActive([statestart[2,i,j] | i in 0..4]))) = ${sbox2};" >> ./iterative_calls_${nr}nr_${sbox}sbox/ASCON_v5_Sbox_${num}.mzn
		take=1
		continue
	fi
	if [[ ${take} -eq 1 ]]; then # this is the first line
		for ((i=0;i<=${#p};i++)); do
			if [[ ${p:$i:1} == 1 ]]; then
				echo "constraint checkActive([statestart[1,i,${i}] | i in 0..4]) = 1;" >> ./iterative_calls_${nr}nr_${sbox}sbox/ASCON_v5_Sbox_${num}.mzn
			fi
		done
		take=2
		continue
	fi
	if [[ ${take} -eq 2 ]]; then # this is the second line
		for ((i=0;i<=${#p};i++)); do
			if [[ ${p:$i:1} == 1 ]]; then
				echo "constraint checkActive([statestart[2,i,${i}] | i in 0..4]) = 1;" >> ./iterative_calls_${nr}nr_${sbox}sbox/ASCON_v5_Sbox_${num}.mzn
			fi
		done
		take=0
		max2; minizinc --solver "chuffed" -a -D "nr = ${nr};" --time-limit 5400000 --output-time --statistics ./iterative_calls_${nr}nr_${sbox}sbox/ASCON_v5_Sbox_${num}.mzn > ./iterative_calls_${nr}nr_${sbox}sbox/results/ASCON_results_${num}.txt &
		num=$((num + 1))
		echo num $num
	fi
done < ASCON_P_${sbox}.txt


nr=6
mkdir -p ./iterative_calls_${nr}nr_${sbox}sbox
mkdir -p ./iterative_calls_${nr}nr_${sbox}sbox/results

num=0
take=0
while read p; do
	if [[ "$p" == *-* ]]; then 
		continue
	fi
	if [[ "$p" == *"["* ]]; then 
		echo ${p}
		echo $num
		cp ASCON_v5_Sbox_${nr}rd.mzn ./iterative_calls_${nr}nr_${sbox}sbox/ASCON_v5_Sbox_${num}.mzn
		read sbox1 sbox2 <<< ${p//[^0-9]/ }
		echo "constraint sum(j in 0..63)(bool2int(checkActive([statestart[1,i,j] | i in 0..4]))) = ${sbox1};" >> ./iterative_calls_${nr}nr_${sbox}sbox/ASCON_v5_Sbox_${num}.mzn
		echo "constraint sum(j in 0..63)(bool2int(checkActive([statestart[2,i,j] | i in 0..4]))) = ${sbox2};" >> ./iterative_calls_${nr}nr_${sbox}sbox/ASCON_v5_Sbox_${num}.mzn
		take=1
		continue
	fi
	if [[ ${take} -eq 1 ]]; then # this is the first line
		for ((i=0;i<=${#p};i++)); do
			if [[ ${p:$i:1} == 1 ]]; then
				echo "constraint checkActive([statestart[1,i,${i}] | i in 0..4]) = 1;" >> ./iterative_calls_${nr}nr_${sbox}sbox/ASCON_v5_Sbox_${num}.mzn
			fi
		done
		take=2
		continue
	fi
	if [[ ${take} -eq 2 ]]; then # this is the second line
		for ((i=0;i<=${#p};i++)); do
			if [[ ${p:$i:1} == 1 ]]; then
				echo "constraint checkActive([statestart[2,i,${i}] | i in 0..4]) = 1;" >> ./iterative_calls_${nr}nr_${sbox}sbox/ASCON_v5_Sbox_${num}.mzn
			fi
		done
		take=0
		max2; minizinc --solver "chuffed" -a -D "nr = ${nr};" --time-limit 5400000 --output-time --statistics ./iterative_calls_${nr}nr_${sbox}sbox/ASCON_v5_Sbox_${num}.mzn > ./iterative_calls_${nr}nr_${sbox}sbox/results/ASCON_results_${num}.txt &
		num=$((num + 1))
		echo num $num
	fi
done < ASCON_P_${sbox}.txt